# Generated by Django 3.2.4 on 2022-04-19 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(max_length=200)),
                ('donor_age', models.IntegerField()),
                ('donor_blood_group', models.CharField(max_length=10)),
                ('donor_email', models.EmailField(max_length=254)),
                ('donor_contact', models.CharField(max_length=20)),
                ('donor_address', models.CharField(max_length=200)),
                ('donor_donated_blood_amt', models.IntegerField()),
                ('donation_date', models.DateField()),
                ('donor_received_blood_amt', models.IntegerField()),
                ('donor_received_blood_group', models.CharField(max_length=10)),
                ('receiving_date', models.DateField()),
            ],
        ),
    ]
